#!/usr/bin/env python
"""
测试80端口重定向server块不被解析为独立站点
"""

from services.config_parser import ConfigParser

def test_redirect_server_block_parsing():
    """测试包含80端口重定向的配置文件解析"""
    print("=" * 80)
    print("测试：80端口重定向server块解析")
    print("=" * 80)
    
    # 模拟生成的包含80端口重定向的Nginx配置
    config_content = """
# example.com - Static Site Configuration
# Generated by easyNginx v1.0 at 2026-01-12
# Performance Baseline: Applied (F5/CIS Best Practices)
# HTTPS Security: Enabled

# HTTP重定向到HTTPS
server {
    listen 80;
    server_name example.com;
    
    # 重定向所有HTTP请求到HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name example.com;
    
    # 性能优化基线 (Performance Baseline)
    keepalive_timeout 65s;
    keepalive_requests 1000;
    
    # Gzip压缩配置
    gzip on;
    gzip_comp_level 6;
    gzip_min_length 1024;
    gzip_vary on;
    gzip_proxied any;
    gzip_types text/plain text/css text/xml text/javascript application/javascript application/xml+rss application/json image/svg+xml font/ttf font/otf;
    
    # 高效传输
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    
    # 请求限制
    client_max_body_size 10m;
    client_body_timeout 12s;
    client_header_timeout 12s;
    send_timeout 10s;
    
    # 日志优化
    access_log off;
    
    error_log logs/example.com_error.log warn;
    
    # 安全加固 (Security Hardening)
    
    # 隐藏版本信息
    server_tokens off;
    
    # 隐藏.开头文件
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
    
    # 请求限制（防DDoS/爆破）
    limit_req zone=api burst=20 nodelay;
    limit_conn addr 20;
    
    # 缓冲区限制（防缓冲区溢出）
    client_body_buffer_size 8k;
    client_header_buffer_size 1k;
    large_client_header_buffers 2 1k;
    
    # 站点配置
    root "/var/www";
    index index.html;
    
    # 主location
    location / {
        try_files $uri $uri/ =404;
        
        # 安全头（基础）
        add_header X-Content-Type-Options nosniff always;
        add_header X-Frame-Options SAMEORIGIN always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    }
    
    # HTTPS配置（可选）
    # 监听端口（SSL）
    listen 443 ssl;
    
    # HTTP/2 支持（Nginx 1.25.1+）
    http2 on;
    
    # SSL证书配置
    ssl_certificate "/path/to/cert.crt";
    ssl_certificate_key "/path/to/key.key";
    
    # TLS协议版本（仅允许1.2和1.3）
    ssl_protocols TLSv1.2 TLSv1.3;
    
    # 强加密套件
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers on;
    
    # SSL会话缓存
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_session_tickets off;
    
    # OCSP Stapling
    ssl_stapling on;
    ssl_stapling_verify on;
    
    # HSTS（强制HTTP转HTTPS）
    add_header Strict-Transport-Security "max-age=31536000 ; includeSubDomains ; preload" always;
}
"""
    
    parser = ConfigParser()
    
    print("\n解析配置...")
    sites = parser.parse_config_content(config_content, "example.com.conf")
    
    print(f"\n解析结果：")
    print(f"  找到的站点数量: {len(sites)}")
    
    for i, site in enumerate(sites, 1):
        print(f"\n  站点 {i}:")
        print(f"    名称: {site.site_name}")
        print(f"    类型: {site.site_type}")
        print(f"    端口: {site.listen_port}")
        print(f"    启用HTTPS: {site.enable_https}")
    
    # 验证结果
    print("\n" + "=" * 80)
    if len(sites) == 1:
        print("[PASS] 正确！只解析出一个站点（80端口重定向块被正确跳过）")
        site = sites[0]
        if site.listen_port == 443 and site.enable_https:
            print("[PASS] 解析出的站点是HTTPS主站点（端口443）")
        else:
            print(f"[FAIL] 解析出的站点不正确: 端口={site.listen_port}, HTTPS={site.enable_https}")
    elif len(sites) == 0:
        print("[FAIL] 没有解析出任何站点")
    else:
        print(f"[FAIL] 解析出多个站点（应该只有1个）: {len(sites)}")
    
    print("=" * 80)

def test_without_redirect():
    """测试没有80端口重定向的配置文件解析"""
    print("\n" + "=" * 80)
    print("测试：没有80端口重定向的配置文件解析")
    print("=" * 80)
    
    config_content = """
server {
    listen 443 ssl;
    server_name example.com;
    
    root "/var/www";
    index index.html;
}
"""
    
    parser = ConfigParser()
    sites = parser.parse_config_content(config_content)
    
    print(f"\n解析结果：")
    print(f"  找到的站点数量: {len(sites)}")
    
    for i, site in enumerate(sites, 1):
        print(f"\n  站点 {i}:")
        print(f"    名称: {site.site_name}")
        print(f"    端口: {site.listen_port}")
    
    print("\n" + "=" * 80)
    if len(sites) == 1:
        print("[PASS] 正确解析出一个HTTPS站点")
    else:
        print(f"[FAIL] 解析出 {len(sites)} 个站点（应该只有1个）")
    print("=" * 80)

if __name__ == "__main__":
    test_redirect_server_block_parsing()
    test_without_redirect()
    
    print("\n" + "=" * 80)
    print("[SUCCESS] 所有测试完成")
    print("修复内容：80端口重定向server块不再被解析为独立站点")
    print("=" * 80)
